config/routes.rb
Rails.application.routes.draw do
  resources :labels
  resources :image_labels
  resources :images
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/image.rb
class Image
  include Mongoid::Document
  include Mongoid::Search

  field :_id, type: String, default: -> { image_id }
  field :image_id, type: String
  field :subset, type: String
  field :original_url, type: String
  field :original_landing_url, type: String
  field :license, type: String
  field :author_profile_url, type: String
  field :author, type: String
  field :title, type: String
  field :original_size, type: String
  field :original_md5, type: String
  field :thumbnail_300k_url, type: String

  has_many :image_labels

  search_in image_labels: :name

  def labels
    Label.in(id: image_labels.pluck(:label_id))
  end

  def label_names
    labels.pluck(:name)
  end
end

app/models/image_label.rb
class ImageLabel
  include Mongoid::Document
  field :name, type: String
  field :confidence, type: Float
  field :source, type: String

  belongs_to :image
end

app/models/label.rb
class Label
  include Mongoid::Document
  field :_id, type: String, default: -> { label_id }
  field :label_id, type: String
  field :name, type: String

  has_many :image_labels

  def images
    Image.in(id: image_labels.pluck(:image_id))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/image_labels_controller.rb
class ImageLabelsController < ApplicationController
  before_action :set_image_label, only: [:show, :edit, :update, :destroy]

  # GET /image_labels
  # GET /image_labels.json
  def index
    @image_labels = ImageLabel.all
  end

  # GET /image_labels/1
  # GET /image_labels/1.json
  def show
  end

  # GET /image_labels/new
  def new
    @image_label = ImageLabel.new
  end

  # GET /image_labels/1/edit
  def edit
  end

  # POST /image_labels
  # POST /image_labels.json
  def create
    @image_label = ImageLabel.new(image_label_params)

    respond_to do |format|
      if @image_label.save
        format.html { redirect_to @image_label, notice: 'Image label was successfully created.' }
        format.json { render :show, status: :created, location: @image_label }
      else
        format.html { render :new }
        format.json { render json: @image_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_labels/1
  # PATCH/PUT /image_labels/1.json
  def update
    respond_to do |format|
      if @image_label.update(image_label_params)
        format.html { redirect_to @image_label, notice: 'Image label was successfully updated.' }
        format.json { render :show, status: :ok, location: @image_label }
      else
        format.html { render :edit }
        format.json { render json: @image_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_labels/1
  # DELETE /image_labels/1.json
  def destroy
    @image_label.destroy
    respond_to do |format|
      format.html { redirect_to image_labels_url, notice: 'Image label was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_label
      @image_label = ImageLabel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_label_params
      params.require(:image_label).permit(:image_id, :label_id, :confidence, :source)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image
              .full_text_search(params[:query])
              .page(params[:page])
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:image_id, :subset, :original_url, :original_landing_url, :license, :author_profile_url, :author, :title, :original_size, :original_md5, :thumbnail_300k_url)
    end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy]

  # GET /labels
  # GET /labels.json
  def index
    @labels = Label.all
  end

  # GET /labels/1
  # GET /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels
  # POST /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to @label, notice: 'Label was successfully created.' }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1
  # PATCH/PUT /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to @label, notice: 'Label was successfully updated.' }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1
  # DELETE /labels/1.json
  def destroy
    @label.destroy
    respond_to do |format|
      format.html { redirect_to labels_url, notice: 'Label was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def label_params
      params.require(:label).permit(:id, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_labels_helper.rb
module ImageLabelsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/image_labels/_form.html.erb
<%= form_for(image_label) do |f| %>
  <% if image_label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image_label.errors.count, "error") %> prohibited this image_label from being saved:</h2>

      <ul>
      <% image_label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_id %>
    <%= f.text_field :image_id %>
  </div>

  <div class="field">
    <%= f.label :label_id %>
    <%= f.text_field :label_id %>
  </div>

  <div class="field">
    <%= f.label :confidence %>
    <%= f.text_field :confidence %>
  </div>

  <div class="field">
    <%= f.label :source %>
    <%= f.text_field :source %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/image_labels/edit.html.erb
<h1>Editing Image Label</h1>

<%= render 'form', image_label: @image_label %>

<%= link_to 'Show', @image_label %> |
<%= link_to 'Back', image_labels_path %>

app/views/image_labels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Image Labels</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Label</th>
      <th>Confidence</th>
      <th>Source</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @image_labels.each do |image_label| %>
      <tr>
        <td><%= image_label.image_id %></td>
        <td><%= image_label.label_id %></td>
        <td><%= image_label.confidence %></td>
        <td><%= image_label.source %></td>
        <td><%= link_to 'Show', image_label %></td>
        <td><%= link_to 'Edit', edit_image_label_path(image_label) %></td>
        <td><%= link_to 'Destroy', image_label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image Label', new_image_label_path %>

app/views/image_labels/new.html.erb
<h1>New Image Label</h1>

<%= render 'form', image_label: @image_label %>

<%= link_to 'Back', image_labels_path %>

app/views/image_labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @image_label.image_id %>
</p>

<p>
  <strong>Label:</strong>
  <%= @image_label.label_id %>
</p>

<p>
  <strong>Confidence:</strong>
  <%= @image_label.confidence %>
</p>

<p>
  <strong>Source:</strong>
  <%= @image_label.source %>
</p>

<%= link_to 'Edit', edit_image_label_path(@image_label) %> |
<%= link_to 'Back', image_labels_path %>

app/views/images/_form.html.erb
<%= form_for(image) do |f| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_id %>
    <%= f.text_field :image_id %>
  </div>

  <div class="field">
    <%= f.label :subset %>
    <%= f.text_field :subset %>
  </div>

  <div class="field">
    <%= f.label :original_url %>
    <%= f.text_field :original_url %>
  </div>

  <div class="field">
    <%= f.label :original_landing_url %>
    <%= f.text_field :original_landing_url %>
  </div>

  <div class="field">
    <%= f.label :license %>
    <%= f.text_field :license %>
  </div>

  <div class="field">
    <%= f.label :author_profile_url %>
    <%= f.text_field :author_profile_url %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :original_size %>
    <%= f.text_field :original_size %>
  </div>

  <div class="field">
    <%= f.label :original_md5 %>
    <%= f.text_field :original_md5 %>
  </div>

  <div class="field">
    <%= f.label :thumbnail_300k_url %>
    <%= f.text_field :thumbnail_300k_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<%= form_tag images_path, method: :get do %>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag 'Search' %>
<% end %>

<div id="gallery">
    <% @images.each do |image| %>
        <% image_url = image.thumbnail_300k_url || image.original_url %>
        <a href="<%= image_url %>">
            <%= image_tag image_url %>
        </a>
    <% end %>
</div>

<%= paginate @images %>

<%= link_to 'New Image', new_image_path %>

<script type="text/javascript">
 $(document).ready(function() {
     $("#gallery").lightGallery();
     $("#gallery").justifiedGallery();
 });
</script>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @image.image_id %>
</p>

<p>
  <strong>Subset:</strong>
  <%= @image.subset %>
</p>

<p>
  <strong>Original url:</strong>
  <%= @image.original_url %>
</p>

<p>
  <strong>Original landing url:</strong>
  <%= @image.original_landing_url %>
</p>

<p>
  <strong>License:</strong>
  <%= @image.license %>
</p>

<p>
  <strong>Author profile url:</strong>
  <%= @image.author_profile_url %>
</p>

<p>
  <strong>Author:</strong>
  <%= @image.author %>
</p>

<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>

<p>
  <strong>Original size:</strong>
  <%= @image.original_size %>
</p>

<p>
  <strong>Original md5:</strong>
  <%= @image.original_md5 %>
</p>

<p>
  <strong>Thumbnail 300k url:</strong>
  <%= @image.thumbnail_300k_url %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/labels/_form.html.erb
<%= form_for(label) do |f| %>
  <% if label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
      <% label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %>
    <%= f.text_field :id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<h1>Editing Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %>

app/views/labels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Labels</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.id %></td>
        <td><%= label.name %></td>
        <td><%= link_to 'Show', label %></td>
        <td><%= link_to 'Edit', edit_label_path(label) %></td>
        <td><%= link_to 'Destroy', label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Label', new_label_path %>

app/views/labels/new.html.erb
<h1>New Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Back', labels_path %>

app/views/labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @label.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @label.name %>
</p>

<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenImages</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>